spring.application.name=backend

# MongoDB Connection
spring.data.mongodb.uri=mongodb+srv://devangsanjaypardeshi_db_user:AeyzMLNXlEd3Ozpm@smarthire.o25oatc.mongodb.net/smarthire?appName=smarthire

# Server port
server.port=8080

# Disable security for development
spring.security.enabled=false