spring.application.name=backend

# MongoDB Connection (from Render env)
spring.data.mongodb.uri=${MONGO_URI}

# JWT secret
app.jwt.secret=${JWT_SECRET:SmartHireDevelopmentJwtSecretKeyForLocalUseOnly2026}

# Server port (Render requirement)
server.port=${PORT:8080}

# Disable security (dev)
spring.security.enabled=false